name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test"